reddit:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: reddit_analytics
      host: localhost
      port: "{{ env_var('CLICKHOUSE_HTTP_PORT') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      secure: False
